//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagneticMonitoringApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MagneticDBContext : DbContext
    {
        public MagneticDBContext()
            : base("name=MagneticDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Generator> Generators { get; set; }
        public virtual DbSet<Measurement> Measurements { get; set; }
        public virtual DbSet<ResultAlgorithm1> ResultAlgorithm1 { get; set; }
        public virtual DbSet<ResultAlgorithm2> ResultAlgorithm2 { get; set; }
    }
}
