//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagneticMonitoringApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Measurement()
        {
            this.ResultAlgorithm1 = new HashSet<ResultAlgorithm1>();
            this.ResultAlgorithm2 = new HashSet<ResultAlgorithm2>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Path1___raw_signal { get; set; }
        public string Path2___fft { get; set; }
        public string Path3___signal_features { get; set; }
        public Nullable<int> GeneratorId { get; set; }
    
        public virtual Generator Generator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultAlgorithm1> ResultAlgorithm1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultAlgorithm2> ResultAlgorithm2 { get; set; }
    }
}
