//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagneticMonitoringApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultAlgorithm2
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Pole1 { get; set; }
        public decimal Pole2 { get; set; }
        public decimal Pole3 { get; set; }
        public decimal Pole4 { get; set; }
        public decimal Pole5 { get; set; }
        public decimal Pole6 { get; set; }
        public decimal Pole7 { get; set; }
        public decimal Pole8 { get; set; }
        public decimal Pole9 { get; set; }
        public decimal Pole10 { get; set; }
        public decimal Pole11 { get; set; }
        public decimal Pole12 { get; set; }
        public decimal Pole13 { get; set; }
        public decimal Pole14 { get; set; }
        public decimal Pole15 { get; set; }
        public decimal Pole16 { get; set; }
        public decimal Pole17 { get; set; }
        public decimal Pole18 { get; set; }
        public decimal Pole19 { get; set; }
        public decimal Pole20 { get; set; }
        public decimal Pole21 { get; set; }
        public decimal Pole22 { get; set; }
        public decimal Pole23 { get; set; }
        public decimal Pole24 { get; set; }
        public decimal Pole25 { get; set; }
        public decimal Pole26 { get; set; }
        public decimal Pole27 { get; set; }
        public decimal Pole28 { get; set; }
        public decimal Pole29 { get; set; }
        public decimal Pole30 { get; set; }
        public decimal Pole31 { get; set; }
        public decimal Pole32 { get; set; }
        public Nullable<int> MeasurementId { get; set; }
    
        public virtual Measurement Measurement { get; set; }
    }
}
